### PR TITLE
Integrate OTPs into rofi-pass

### PR DESCRIPTION
**Pull request by moviuro**
I edited rofi-pass to handle OTP (thanks to [rofi-otp(1)](https://github.com/tadfisher/pass-otp)).

A new menu item appears, once you selected an item:

    Choose a Field to type>
    ---
    autotype
    OTP
    pass
    user

The OTP is generated when we ask `rofi-pass` to type it.

It works just right on my machine, further testing would be helpful :smile:

### CODE REVIEW

**Comment by carnager** [comment]
Can anyone who actually uses OTP comment on this?

**Comment by benhartley** [comment]
Referencing #50 for conversation

**Comment by moviuro** [comment]
My PR is missing on the `autopass()` section. (https://github.com/carnager/rofi-pass/blob/91a0829b690767b1734487f4af8766a586d7b1b7/rofi-pass#L80-L85)

Adding yet another switch/case for `:otp` sounds... bad. We will need to work on this function, so that `:unknown_keyword` types the result of `pass unknown_keyword $selected_password`

**Comment by errge** [comment]
@carnager I'm using OTP and (naturally) I prefer my own #94 PR.  The main reason why I prefer that is that it provides a general framework for calling out from rofi-pass to other utilities.  So when my workplace provides me with a random other kind of OTP for which I have to use other binary than the "pass-otp" pass plugin, then I can hack it up.

So how I see it is that I would like to get #94 merged no matter what, because it provides me flexibility that I already use and need in the future (calling out to shell).  It's very powerful in the right hands and makes rofi-pass a much better tool for powerusers.  And #94 can also be used as an easy way for users to use OTP, I added an example to the doc in the PR.

If for the most important and frequent OTPs we add some specific support via this PR, that's fine by me, but I hope that someone will have time to take a look at #94 soon, so we provide the generic hackability that I was trying to get to there.

**Comment by carnager** [comment]
Ok, some comments about #94 and #101.

#101 has a simple aproach which does not need any knowledge about writing scripts. Yet it lacks the flexibility of #94, which with the current mess with OTP being a standard with many exceptions, is sadly needed.

But I am not sure, how I like the idea that pass entries can run arbitrary shell commands.

I would like to propose a variation of #94:
Let rofi-pass ship otp profiles, with custom commands and in the pass entries simply define the profile to use. This way we can ship different otp methods with rofi-pass instead of explaining users how to script it themselves. Profiles would have to be shipped unencrypted though, not sure if that can be a problem.

What do you think?

**Comment by errge** [comment]
@carnager First of all thank you for your response and for reacting so quickly to my ping.

I like the profile idea and I agree with the reasoning that users should not need to be shell experts to use OTP.  But I don't agree with the dislike of arbitrary shell commands.

I think you are right in that we shouldn't require arbitrary shell programming for a standard feature like OTP, but I also think we should not forbid running arbitrary shell scripts for power-users, so this is a feature that I would like to have in the long run.

So let me reword your proposal to my liking and then we can continue to iterate with your criticism of that :)

My proposal is:
  - to have the #94 like shell feature, but document it as a "power-user" feature and remove it from the OTP documentation and remove the OTP examples,
  - implement your profile idea on top of the shell implementation,
  - ship OTP profiles as the first use case of the above,
  - document OTP profile usage with examples.

From security standpoint I wouldn't be afraid of the shell commands, the user still has to add them explicitly to his pass entries.  For the OTP use case we will ship with the profiles and therefore no arbitrary shell commands will be involved there.  If you are really worried about the security + arbitrary shell commands, it's fine with me if those entries are only parsed if rofi-pass has been started with --enable-shell-entries or something like that.

I haven't validated on the code level the difficulty of all this, can try to do some work on Friday if we reach some consensus by then.

**Comment by moviuro** [comment]
Promoting #94 to "power-user" feature sounds sane. Then #101 fixes a sort of well-established standard (`otpauth://`) for simple OTP entries.

I'm not really sure of what kind of examples we can add to #94 though. `cat /etc/machine-id`, `date`?...

**Comment by errge** [comment]
@moviuro my current usage for the shell would be a proprietary logging password storage solution.  So it's basically a "provide you with a secret in exchange of creating some audit log" system for which the shell feature can call the client.  machine-id and date are good examples too, I think, I can mention them.

**Comment by carnager** [comment]
@moviuro atm you are hardcoding :otp to use pass-otp. If I were to go the profile route, `:otp` would only define the `pass-otp` profile (which we ship). That profile is a simple shell script that executes the needed `pass otp foobar` command. Does this sound reasonable to you?

@errge the shell command stuff in #94 would not be purely otp related anymore. Most common use cases we should ship as a profile. 
So I suggest promoting #94 not as a otp feature, but a general run_command feature, which can be used to cover more exotic scenarios.

Sounds right?

**Comment by errge** [comment]
@carnager yes, that sounds right!  The only thing that I ask for is that it's possible for the end-user to run anything even if we don't have a profile for that.  But I agree that we should ship other, interesting profiles if we come up with something nice!  OTP is definitely just one of the use cases.

I will work on this on Friday and let's see how it turns out.

**Comment by carnager** [comment]
Ok, so let's keep these issues separate. #101 is about the otp part, for this the following things are needed:

* global directory of otp profiles.
* scanning of otp profiles directory `otp_methods=(*)`
* :otp keyword should check above otp_methods array and run it, if present
* we should think about how needed information is passed to the otp scripts and how results are captured.
* Documentation

In future we should also think about how to insert stuff to pass files, but reading them should be the priority for now.

@errge As for the run_command stuff, we should move the discussion about that to #94.

**Comment by moviuro** [comment]
I'm not sure what I should write now. 450f6ef does what I expect in the most simple, stupid, drop-in way.

pass-otp (https://github.com/tadfisher/pass-otp) is the de facto extension for managing OTPs within pass(1), it's included in the archwiki (https://wiki.archlinux.org/index.php/Pass#Extensions) and one of the few pass extensions in the Archlinux repos.

**Comment by carnager** [comment]
@moviuro thats fine. I just want :otp to be more flexible. Which basically only means I would like to have `printf '%s' "$(PASSWORD_STORE_DIR="${root}" pass otp ${selected_password})" | xdotool type --clearmodifiers --file -;;` in a separate script. Let's name it `pass-otp.otp`. And in your actual pass file you then define `":otp") passs-otp.otp`.

**Comment by moviuro** [comment]
BTW, we really should put `"$(PASSWORD_STORE_DIR="${root}" pass xxxxxx ${selected_password})"` in a wrapper function. It's all over the place.

**Comment by moviuro** [comment]
OK, so now you can set:

```
otp_method: echo "haha, jk, no OTP"
```
```
otp_method: /otp/proprietary_otp_gen --some-option some values
```

And... oh wait, the OTP field won't appear if there's only the `otp_method:` field.

**Pull request merged**
