### PR TITLE
added support for User. if user is not set

### PR DESCRIPTION
**Pull request by onkelpit**
Hey,

i've added support for "User" notation added by gopass.

### CODE REVIEW

**Comment by carnager** [comment]
Hmm, this would basically break

**Comment by carnager** [comment]
Hmm, still trying to think about possible side effects. Until then: gopass actually supports yaml syntax out of the box? that's pretty neat.

**Comment by dvogt23** [comment]
I'm also interessted in changing the possible entries to case-insensitive, if possible :+1:

**Comment by carnager** [comment]
I have started a gopass branch, let's see how this turns out in the end

**Pull request closed without merging**
