### PR TITLE
Fix copy username action (and some miscellaneous cleanup).

### PR DESCRIPTION
**Pull request by dkasak**

### CODE REVIEW

**Comment by carnager** [comment]
Thanks. In future The help should be transformed into a herdoc. Also other echo calls should be made into printf

**Comment by dkasak** [comment]
I agree, I saw that some of those have already been suggested in a PR by moviuro. I might get around to doing it when I catch some time.

**Comment by carnager** [comment]
I have manually commited his proposed changes already so spare your time. The printf calls remain though.

**Comment by dkasak** [comment]
Awesome, thanks!

**Comment by carnager** [comment]
about echo. I wonder if a replace `s/echo -e/printf '%s\n'/g` would be enough

**Comment by dkasak** [comment]
On its own, I'd say no, given things like this exist

    echo -e "Yes\nNo"

`printf` doesn't interpret escape codes encountered in string arguments unless you use `%b` instead of `%s`. However, there aren't that many `echo -e` calls so this could be fixed manually.

**Comment by carnager** [comment]
I went ahead and changed all echos in the printf branch: f48b762134198fb6cc900da221624fbf9f6d92c6
Maybe you would like to have a look if I screwed up anywhere

**Comment by carnager** [comment]
Ok, this commit broke autotype and insertpass. fixed now.

**Pull request merged**
