### PR TITLE
Syntax enhancements

### PR DESCRIPTION
**Pull request by moviuro**
Minor aesthetic changes.

You should test the autotype feature, as I don't use it and am not sure that my changes didn't introduce some regressions :roll_eyes:

Cheers,

### CODE REVIEW

**Comment by carnager** [comment]
Ah nice, I planned to change most of these a long time ago :)
Will test it these days and then happily merge

**Comment by carnager** [comment]
Sorry, real life was too busy. Would you mind updating this patch to master? I should have the time to test if it breaks anything now.

**Comment by carnager** [comment]
Ok, I merged these manually and credited you in commit message. Thanks

**Comment by moviuro** [comment]
Sorry, I was busy IRL! Thanks :smile:

**Pull request closed without merging**
