### PR TITLE
get rid of the empty line after autotype

### PR DESCRIPTION
**Pull request by aminb**

### CODE REVIEW

**Comment by moviuro** [comment]
BTW, we should probably drop `echo(1)` completely and switch to `printf`.

**Comment by carnager** [comment]
> BTW, we should probably drop echo(1) completely and switch to printf.

exactly what I thought yesterday. I already removed like 90% of all echo calls a while ago, but some are still left.

**Comment by aminb** [comment]
Pardon my ignorance, but are there any particular benefits in using `printf` over `echo`? (besides string formatting, of course, when needed). Are there any noticeable performance gains?

**Comment by aminb** [comment]
@carnager thanks for sharing; that was quite insightful. I added another commit to replace the remaining `echo`s with `printf`s.

**Pull request merged**
