### PR TITLE
Platform depending detection of grep

### PR DESCRIPTION
**Pull request by Xanderio**
This change is need so the rofi-pass will work of FreeBSD

### CODE REVIEW

**Comment by Xanderio** [comment]
There is no problem with my installation. /usr/bin/grep is just first in PATH and so it is used. 
And i don't see any errors the list is just emtpy.

**Comment by Xanderio** [comment]
The issue seems to be in `list_passwords`. Freebsd find dos not seem to have a -printf option.

**Comment by moviuro** [comment]
See https://github.com/carnager/rofi-pass/commit/2ac1bef1e09de1acf0376a7c707af005dbde6d36#diff-9c2e6bc22af7bed199ed145d116eaaf0L62 . `list_passwords` doesn't use `find -printf` anymore... https://github.com/carnager/rofi-pass/blob/a2acca731dfa0b7cd5df265796e6400d36fddb17/rofi-pass#L63-L69

**Comment by Xanderio** [comment]
when will this patch be part of a release, so that i can package rofi-pass for FreeBSD?

**Comment by moviuro** [comment]
@carnager, see above

**Comment by carnager** [comment]
Yeah, I guess it's time

**Comment by carnager** [comment]
https://github.com/carnager/rofi-pass/releases/tag/2.0.2

**Pull request closed without merging**
