### PR TITLE
add ROFI_PASS_CONFIG environment variable

### PR DESCRIPTION
**Pull request by lsbloxx**

### CODE REVIEW

**Comment by carnager** [comment]
thanks

**Comment by moviuro** [comment]
To avoid conflicts, I would use here https://github.com/carnager/rofi-pass/pull/118/files#diff-9c2e6bc22af7bed199ed145d116eaaf0R721:

```
: "${ROFI_PASS_CONFIG:="$HOME/.config/rofi-pass/config"}"
```

Which: if unset, sets ROFI_PASS_CONFIG; if set, does nothing.

This prevents https://github.com/carnager/rofi-pass/pull/118/files#diff-9c2e6bc22af7bed199ed145d116eaaf0R729 from sourcing a *second* file.

I think we must have a cleaner workflow to use in the following order of preference:

1. User supplied config file (ROFI_PASS_CONFIG)
2. Default location for user config ($HOME/.config/rofi-pass/config)
3. Default system-wide config (/etc/rofi-pass.conf)

**Comment by lsbloxx** [comment]
Is there any problem sourcing multiple files? Would it not just overwrite previously loaded settings? Sourcing multiple config files could also be a feature. Don't get me wrong. I totally see your point @moviuro. It is probably cleaner your way. I just want to know. :)

**Comment by moviuro** [comment]
Sourcing multiple files could indeed rewrite settings, but also set things that you don't want set.

If a global file (owned by root in /etc) sets $FOOBAR but your local (personal) file doesn't, I expect the global file to be ignored and $FOOBAR to be unset for my user.

For example, [ssh_config(5)](https://www.freebsd.org/cgi/man.cgi?query=ssh_config&sektion=5) says it uses the first set value. [makepkg.conf(5)](https://www.archlinux.org/pacman/makepkg.conf.5.html) OTOH says it overrides system config with the local config. Just food for thought.

**Comment by carnager** [comment]
Well I am open for clearer solutions. what rofi-pass does right now is:
1. set internal default values.
2. source global config
3. source user config
4. source custom config, if present.

I agree that this seems a bit messy. I am open for better solutions.

**Pull request merged**
