### PR TITLE
Add support for local 2FA code generation

### PR DESCRIPTION
**Pull request by jshuping**
(Disclaimer: depending on your overall security configuration,
this approach may be insecure for you. Use at your own risk.)

With this addition you can insert your 2FA secrets (from sites like
Google) into pass, and then use rofi-pass to generate the tokens
and type them in for you.

To get your secrets, you will need to disable/re-enable 2FA for a
particular account, and when shown the new QR code, click the link to instead
show the secret token, which is what you put into pass (and you probably
also want to scan the new code on your phone as well).

Don't forget to set a hotkey in your rofi-pass config (see
config.example)

### CODE REVIEW

**Comment by carnager** [comment]
could you cast this? I am not using app specific passwords in google,  but this might be handy

**Comment by jshuping** [comment]
Hi and thanks for rofi-pass!  I'm not sure I understand, what do you mean by "cast this" ?

Also, to make sure it's clear, this is not for google's app-specific passwords, this is for any site that supports 2-factor / 2-step authentication (HOTP/TOTP).  For example:
https://www.google.com/landing/2step/
https://help.github.com/articles/about-two-factor-authentication/
https://support.coinbase.com/customer/portal/articles/1658338-how-do-i-set-up-2-factor-authentication-with-authy-

I'm happy to make any changes you suggest. Thanks!

**Comment by carnager** [comment]
hmmm... in the screencast it seems this needs an extra password file for the sites. it would be much preferable if this was integrated into existing files?

**Comment by jshuping** [comment]
I've never done any python3 conversion, but I can try? 
btw I considered putting the 2fa secret in the same pass entry, but didn't like putting all the eggs in one basket, and it leaves open the possibility to store the 2fa secret in a separate password-store under a different gpg key.

**Comment by carnager** [comment]
i kinda like the feature, but it defeats the purpose of a secure password manager in a way. 2FA is meant to be generated on a different device, that's the whole security idea behind it. This and the fact that I wouldn't be able to maintain it, I have to close this one :)

**Comment by pigmonkey** [comment]
This would actually be very useful for some entries I have in a shared pass repo.

For something like a Google or AWS account that multiple people have access to, there is currently no good way to enable 2FA. This solves that. It introduces some new security considerations, but I think anyone already using pass is capable of competently evaluating those for their own threat profile.

**Pull request closed without merging**
