### PR TITLE
Add support for multiple roots

### PR DESCRIPTION
**Pull request by errge**
These multiple roots can be given with the --roots argument and
navigation is supported with Shift+Left and Shift+Right

Happy to call this current implementation a WIP and add documentation or additional fixes if you think of some interaction that I haven't.

So this is not a request to merge this "as-is", more like a request for review to know if you like the idea and willing to have something like this.  If you do, please provide feedback that on which parts do I have to work on to make this mergeable!

Cheers!

### CODE REVIEW

**Comment by carnager** [comment]
what‘s the use of 

```
   -kb-mode-previous ""        
   -kb-mode-next ""
```

It‘s never used anywhere.

**Comment by carnager** [comment]
Probably a good idea.
What I don‘t like is that there is `--root` and `--roots` now. IMHO those should be merged.

**Comment by errge** [comment]
Hmm, good point, I will take a look for the possibility of merging these two concepts.

I guess what you mean is to have only `--roots` and document, that you can use it with only one, right?  As a backward compatibility, I will just make `--root` an alias to `--roots`, so people don't have to change their config files.

**Comment by carnager** [comment]
You could also just use `--root` and document that it can actually have multiple arguments.

**Comment by errge** [comment]
Right, `--roots` is currently only used by me, so I think this is the easiest way to go, I will get to it soon!

**Comment by errge** [comment]
Hey, I pushed my new proposal, please take a look!

**Comment by carnager** [comment]
I made the vault appear as a message now.

**Comment by carnager** [comment]
and thanks, nice idea

**Pull request merged**
